### ISSUE TITLE
Establish Server Client Archiecture

### ISSUE THREAD

**Issue by EliCDavis** [EliCDavis/ProjectAngelus#4]
Right now builds use localhost to connect with each other and interact.  This will not work when we want to play together and we'll have to have some external server set up to connect users.

**Comment by wesstr** [comment]
#  Server Hosting
* Unity provides free server hosting for testing purposes
## How to use 
* In the networking UI do the following
  * Enable Match Maker -> Create Internet Match and give it a name -> This should spawn you in
* For another person to join 
  * Enable Match Maker -> Find Internet Match -> Join:[name of room]
  * This should now spawn you in selected room
### Resolved in
#6
